### ISSUE TITLE
Demo server - application error

### ISSUE THREAD

**Issue by etlam** [meain/gh-issues-to-rss#4]
The demo server does not work any longer:
https://gh-issues-to-rss.herokuapp.com/

Heroku returns:

> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
> heroku logs --tail

**Comment by meain** [comment]
I had this published on a Heroku account on their free tier. Looks like I have run out of their monthly quota. :D 

_I have seen some traffic to this and so have thought about hosting it on my actual server for public use but have not decided on it. In any case you can always self host this if you like. ;)_

**Comment by meain** [comment]
I have been meaning to try out fly.io for some time. They also have a much more workable free tier. Had some time today and moved it over there. You can now use https://gh-issues-to-rss.fly.dev/ instead of the previous one. I am still figuring out some details but this should be good at least until I start hitting rate-limiting from GitHub api. 😅
